In [1]:
import numpy as np
import random
from anomaly import AnomalyScore


In [2]:
# Generating a random adjacency matrix with 1s and 0s
num_rows = 21
num_cols = 50

adjacency_matrix = np.random.randint(0, 2, size=(num_rows, num_cols))

adjacency_matrix

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 1, 1, ..., 0, 0, 1]])

In [3]:
average_ratings = np.random.randint(1, 6, size=(num_cols,))
average_ratings

array([1, 5, 3, 5, 3, 1, 2, 2, 5, 2, 4, 5, 1, 5, 4, 4, 1, 3, 3, 3, 5, 3,
       1, 4, 2, 1, 1, 3, 1, 4, 3, 4, 4, 1, 4, 1, 4, 4, 3, 5, 3, 3, 3, 3,
       5, 3, 4, 1, 2, 4])

In [4]:
ratings_matrix = np.random.randint(1, 6, size=(num_rows, num_cols)) * adjacency_matrix
ratings_matrix

array([[0, 5, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 4, 0],
       [3, 0, 0, ..., 0, 3, 1],
       ...,
       [0, 0, 4, ..., 0, 0, 0],
       [2, 3, 0, ..., 5, 0, 0],
       [0, 5, 5, ..., 0, 0, 2]])

In [5]:
review_times = np.random.randint(0,100, size=num_rows)
review_times

array([10, 56, 21, 93, 94, 85, 26, 20,  1, 77, 49, 93, 17, 49, 20, 41, 21,
       43, 70, 52,  8])

In [6]:
leaves = [random.sample(range(0, 10), max(1, y // 10)) for y in range(2, 102)]
mapping = np.array(list(range(10)))

In [7]:
AS = AnomalyScore(leaves,mapping,adjacency_matrix,average_ratings,ratings_matrix,review_times,100)
AS.adj

array([[0, 1, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 1, 0, 0],
       [0, 1, 1, ..., 0, 0, 1]])

In [8]:
AS.rating_matrix

array([[0, 5, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 4, 0],
       [3, 0, 0, ..., 0, 3, 1],
       ...,
       [0, 0, 4, ..., 0, 0, 0],
       [2, 3, 0, ..., 5, 0, 0],
       [0, 5, 5, ..., 0, 0, 2]])

In [9]:
AS.review_times

array([10, 56, 21, 93, 94, 85, 26, 20,  1, 77, 49, 93, 17, 49, 20, 41, 21,
       43, 70, 52,  8])

In [10]:
l = AS.generate_anomaly_scores()

In [11]:
l

[2.2592307692307694,
 1.7842857142857143,
 2.1242105263157893,
 1.5,
 2.4,
 1.7842857142857143,
 2.4,
 2.6695652173913045,
 2.316923076923077,
 2.1242105263157893,
 1.79,
 1.7842857142857143,
 1.35,
 1.7842857142857143,
 1.7842857142857143,
 1.8807692307692307,
 1.7842857142857143,
 1.8807692307692307,
 23.666847379993424,
 22.132968801495625,
 22.351045724572547,
 21.24986184268248,
 22.057968801495626,
 20.88507923398683,
 22.13415836518541,
 22.81139701133665,
 22.322199570726394,
 18.79217459289637,
 41.002147001702,
 47.63972842703982,
 46.90787370538906,
 45.30791050059351,
 50.36929348297636,
 48.42896741326218,
 46.56468529959196,
 46.78171985923521,
 49.65666953055636,
 39.5138321485548,
 55.75717034138387,
 50.81587001331506,
 57.53072898838862,
 53.17219164399501,
 55.038162418437395,
 50.778370013315055,
 56.68380897753004,
 56.843040941218526,
 56.903700281877875,
 55.22064362144491,
 58.093476540771235,
 59.11426253224717,
 55.26787160278072,
 59.79706260575092,
 58.73598

In [12]:
max(enumerate(l))

(99, 66.53749311048827)

In [13]:
def min_max_scaling(data):
    min_val = min(data)
    max_val = max(data)
    scaled_data = [(x - min_val) / (max_val - min_val) for x in data]
    return scaled_data

min_max_scaling(l)

[0.013756354475041819,
 0.006570596191124637,
 0.011713543798478252,
 0.0022694493423292324,
 0.015886145396304632,
 0.006570596191124637,
 0.015886145396304632,
 0.01996457609846152,
 0.014629219606706904,
 0.011713543798478252,
 0.006657051404165752,
 0.006570596191124637,
 0.0,
 0.006570596191124637,
 0.006570596191124637,
 0.008030359211318826,
 0.006570596191124637,
 0.008030359211318826,
 0.33764636406258636,
 0.3144392991880215,
 0.3177387293857155,
 0.3010781891421225,
 0.3133045745168569,
 0.2955591514661392,
 0.31445729688491114,
 0.3247036888856302,
 0.317302296819883,
 0.26389421105760225,
 0.599923592899698,
 0.700347958235629,
 0.6892752434574232,
 0.6650683405049284,
 0.7416453557092293,
 0.7122888775571151,
 0.6840829187785482,
 0.6873665783695155,
 0.7308635959749117,
 0.5774058918020063,
 0.8231621129949881,
 0.7484019077964083,
 0.8499954563618364,
 0.7840522582968267,
 0.8122837659425856,
 0.7478345454608257,
 0.8371818426175134,
 0.8395909684526508,
 0.840508723791