In [1]:
import numpy as np

# Generating a random adjacency matrix with 1s and 0s
num_rows = 21
num_cols = 50

adjacency_matrix = np.random.randint(0, 2, size=(num_rows, num_cols))

print(adjacency_matrix)


[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [1 0 0 ... 1 0 1]]


In [2]:
outer_array = np.array([
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1]
])


In [4]:
np.sum(outer_array)

8

In [11]:
from bitarray import bitarray

# Example bitarray
ba = bitarray('1000')

# Count the number of ones (set bits) in the bitarray
count_ones = ba.count()
print(count_ones)  # Output: 4 (count of ones in the bitarray)


1
1


In [22]:
import numpy as np
from functools import reduce

# Example array containing arrays
arrays = [
    np.array([1, 2, 3, 4,5]),
    np.array([3, 4, 5, 6]),
    np.array([2, 4, 6, 5,8])
]

# Find the intersection of all arrays in the list
intersection = reduce(np.union1d, arrays)

print(intersection)


[1 2 3 4 5 6 8]


In [ ]:
def jaccard_similarity( s1, s2):
        """
        Compute Jaccard similarity between two NumPy arrays.

        INPUTS:
        s1 (ndarr) - first array.
        s2 (ndarr) - second array.
        
        OUTPUTS:
        js -  Jaccard similarity coefficient.
        """
        intersection = np.intersect1d(s1, s2)
        union = np.union1d(s1, s2)
        
        # Handle zero division error if union is empty
        if len(union) == 0:
            return 0.0
        
        js = len(intersection) / len(union)
        return js
    
def sum_jaccard(self, arrays):
    # Compute Jaccard similarity between all pairs and sum the scores
    similarity_scores = [
        self.jaccard_similarity(arrays[i], arrays[j])
        for i in range(len(arrays))
        for j in range(i + 1, len(arrays))
    ]
    
    return sum(similarity_scores)


In [23]:
import numpy as np
from scipy.sparse import csr_matrix

# Assuming csr_matrix is your CSR matrix
# Example csr_matrix creation
data = np.array([[1, 2, 0], [0, 0, 3], [4, 0, 5]])  # Example data for the CSR matrix
csr_matrix = csr_matrix(data)

# Compute the sum along rows (axis=1)
sum_per_row = csr_matrix.sum(axis=1)

print("Sum per row:")
print(sum_per_row)


Sum per row:
[[3]
 [3]
 [9]]
