In [1]:
import numpy as np

# Generating a random adjacency matrix with 1s and 0s
num_rows = 21
num_cols = 50

adjacency_matrix = np.random.randint(0, 2, size=(num_rows, num_cols))

print(adjacency_matrix)


[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [1 0 0 ... 1 0 1]]
