In [1]:
import numpy as np

# Generating a random adjacency matrix with 1s and 0s
num_rows = 21
num_cols = 50

adjacency_matrix = np.random.randint(0, 2, size=(num_rows, num_cols))

print(adjacency_matrix)


[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [1 0 0 ... 1 0 1]]


In [2]:
outer_array = np.array([
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1]
])


In [4]:
np.sum(outer_array)

8

In [11]:
from bitarray import bitarray

# Example bitarray
ba = bitarray('1000')

# Count the number of ones (set bits) in the bitarray
count_ones = ba.count()
print(count_ones)  # Output: 4 (count of ones in the bitarray)


1
1


In [22]:
import numpy as np
from functools import reduce

# Example array containing arrays
arrays = [
    np.array([1, 2, 3, 4,5]),
    np.array([3, 4, 5, 6]),
    np.array([2, 4, 6, 5,8])
]

# Find the intersection of all arrays in the list
intersection = reduce(np.union1d, arrays)

print(intersection)


[1 2 3 4 5 6 8]
