In [1]:
import numpy as np

# Generating a random adjacency matrix with 1s and 0s
num_rows = 21
num_cols = 50

adjacency_matrix = np.random.randint(0, 2, size=(num_rows, num_cols))

print(adjacency_matrix)


[[1 0 0 ... 1 1 1]
 [1 0 0 ... 1 1 0]
 [0 1 1 ... 1 1 1]
 ...
 [1 0 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 [1 0 0 ... 1 0 1]]


In [2]:
outer_array = np.array([
    [1, 0, 1, 0, 1],
    [0, 1, 0, 1, 0],
    [1, 1, 0, 0, 1]
])


In [4]:
np.sum(outer_array)

8

In [11]:
from bitarray import bitarray

# Example bitarray
ba = bitarray('1000')

# Count the number of ones (set bits) in the bitarray
count_ones = ba.count()
print(count_ones)  # Output: 4 (count of ones in the bitarray)


1
1


In [22]:
import numpy as np
from functools import reduce

# Example array containing arrays
arrays = [
    np.array([1, 2, 3, 4,5]),
    np.array([3, 4, 5, 6]),
    np.array([2, 4, 6, 5,8])
]

# Find the intersection of all arrays in the list
intersection = reduce(np.union1d, arrays)

print(intersection)


[1 2 3 4 5 6 8]


In [ ]:
def jaccard_similarity( s1, s2):
        """
        Compute Jaccard similarity between two NumPy arrays.

        INPUTS:
        s1 (ndarr) - first array.
        s2 (ndarr) - second array.
        
        OUTPUTS:
        js -  Jaccard similarity coefficient.
        """
        intersection = np.intersect1d(s1, s2)
        union = np.union1d(s1, s2)
        
        # Handle zero division error if union is empty
        if len(union) == 0:
            return 0.0
        
        js = len(intersection) / len(union)
        return js
    
def sum_jaccard(self, arrays):
    # Compute Jaccard similarity between all pairs and sum the scores
    similarity_scores = [
        self.jaccard_similarity(arrays[i], arrays[j])
        for i in range(len(arrays))
        for j in range(i + 1, len(arrays))
    ]
    
    return sum(similarity_scores)


In [47]:
import numpy as np
from scipy.sparse import csr_matrix

# Create two matrices of the same dimensions (random example)
dense_matrix = np.array([[1.2, 2, 3.5], [0, 3, 4], [5.6, 0, 6.1]])
sparse_data = [[0, 0, 1], [0, 0, 1], [1, 0, 1]]
sparse_matrix = csr_matrix(sparse_data)

# Perform element-wise multiplication to extract nonzeros
result_matrix = dense_matrix * sparse_matrix.toarray()
data2 = np.array([[0, 0, 1], [0, 0, 1], [1, 0, 1]])

norm = sparse_matrix @ [1,1,1]

print(result_matrix)
print(result_matrix-data2)
print(np.abs(result_matrix-data2) @ [1,1,1] / norm) 

[[0.  0.  3.5]
 [0.  0.  4. ]
 [5.6 0.  6.1]]
[[0.  0.  2.5]
 [0.  0.  3. ]
 [4.6 0.  5.1]]
[2.5  3.   4.85]


In [60]:
large = np.array(range(21))

shuffled_indices = np.random.permutation(num_rows)

# Calculate the number of rows for each group
group_size = num_rows // 3

# Split the shuffled indices into three equal-sized groups
group1_indices = shuffled_indices[:group_size]
group2_indices = shuffled_indices[group_size:2 * group_size]
group3_indices = shuffled_indices[2 * group_size:]

# Use the indices to split the matrix into three groups
group1 = large[group1_indices]
group2 = large[group2_indices]
group3 = large[group3_indices]

print(large)
print(group1,group2,group3)
leaves = [[1],[1,2],[6,1,2,4,3]]
for leaf in leaves:
    print(group1[leaf])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[19  1 16 17  8 13  9] [20  2 12  7 11 15 14] [ 5  0  6 18 10  4  3]
[1]
[ 1 16]
[ 9  1 16  8 17]


In [63]:
print(large)
print(group1,group2,group3)
leaves = [[1],[1,2],[6,1,2,4,3]]
for leaf in leaves:
    print(group1[leaf])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[19  1 16 17  8 13  9] [20  2 12  7 11 15 14] [ 5  0  6 18 10  4  3]
[1]
[ 1 16]
[ 9  1 16  8 17]


In [64]:
print(np.ones(2))

[1. 1.]
